### ISSUE TITLE
[Design] Create Design Prototype

### ISSUE THREAD

**Issue by jirheee** [CS492-FE-Dev-Team-Project/FE-Dev-Client#3]
## Description
본격적으로 개발을 하기 전에, 앱 기획 중 구체화되지 않은 부분을 디자인 프로토타입을 만들어서 완전히 구체화

## Todo
- [x] 스케치 수준이 아닌, 완성본에 가까울 프로토타입 (최대한 보고 그대로 만들 수 있도록)
- [x] 유저가 앱을 활용하는 플로우를 구체적으로 설계 (어떤 버튼을 눌렀을 떄 어떤 화면으로 전환되는지 등)

**Comment by jirheee** [comment]
[디자인 프로토타입 링크](https://www.figma.com/file/lGLVGwDbbPMwe4s25umpvO/LiveClass-UI-Prototype?node-id=702%3A8721)

**Comment by jirheee** [comment]
강의자의 Lecture Configuration UI 디자인 필요
- [ ] Add Playlist
- [ ] Add quiz/vote

**Comment by jirheee** [comment]
오늘 이야기한 것 기반으로 더 깔끔하게 UI 설계하기
